// <auto-generated />
using System;
using FindJobsApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FindJobsApplication.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FindJobsApplication.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Avt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AdminId");

                    b.HasIndex("UserId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            Avt = "",
                            Cover = "",
                            Name = "John Doe",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("FindJobsApplication.Models.Certification", b =>
                {
                    b.Property<int>("CertificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificationId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CertificationId");

                    b.ToTable("Certifications");

                    b.HasData(
                        new
                        {
                            CertificationId = 1,
                            Description = "Chứng chỉ phát triển phần mềm.",
                            Name = "Lập trình viên được chứng nhận",
                            Subject = "Kỹ sư phần mềm"
                        },
                        new
                        {
                            CertificationId = 2,
                            Description = "Chứng chỉ quản lý dự án.",
                            Name = "Quản lý dự án được chứng nhận",
                            Subject = "Người quản lý dự án"
                        },
                        new
                        {
                            CertificationId = 3,
                            Description = "Chứng chỉ chuyên sâu về an ninh mạng.",
                            Name = "Chuyên gia bảo mật mạng",
                            Subject = "An ninh mạng"
                        },
                        new
                        {
                            CertificationId = 4,
                            Description = "Chứng chỉ quản lý và bảo trì hệ thống IT.",
                            Name = "Chuyên gia quản lý hệ thống",
                            Subject = "Quản trị hệ thống"
                        },
                        new
                        {
                            CertificationId = 5,
                            Description = "Chứng chỉ phát triển ứng dụng di động.",
                            Name = "Chuyên gia phát triển ứng dụng di động",
                            Subject = "Phát triển ứng dụng"
                        },
                        new
                        {
                            CertificationId = 6,
                            Description = "Chứng chỉ về phân tích và xử lý dữ liệu lớn.",
                            Name = "Chuyên gia phân tích dữ liệu",
                            Subject = "Phân tích dữ liệu"
                        },
                        new
                        {
                            CertificationId = 7,
                            Description = "Chứng chỉ về tiếp thị kỹ thuật số và truyền thông trực tuyến.",
                            Name = "Chuyên gia marketing kỹ thuật số",
                            Subject = "Marketing kỹ thuật số"
                        },
                        new
                        {
                            CertificationId = 8,
                            Description = "Chứng chỉ về thiết kế và kiến trúc phần mềm.",
                            Name = "Kiến trúc sư phần mềm",
                            Subject = "Thiết kế phần mềm"
                        },
                        new
                        {
                            CertificationId = 9,
                            Description = "Chứng chỉ về quản lý và triển khai DevOps.",
                            Name = "Chuyên gia DevOps",
                            Subject = "DevOps"
                        },
                        new
                        {
                            CertificationId = 10,
                            Description = "Chứng chỉ chuyên sâu về phát triển trí tuệ nhân tạo.",
                            Name = "Chuyên gia AI",
                            Subject = "Trí tuệ nhân tạo"
                        });
                });

            modelBuilder.Entity("FindJobsApplication.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIBehind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIFront")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialMedia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("UserId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Address = "123 Street",
                            Avt = "",
                            City = "City",
                            Country = "Country",
                            Cover = "",
                            Description = "Skilled developer.",
                            FirstName = "Jane",
                            LastName = "Doe",
                            Phone = "1234567890",
                            PostalCode = "12345",
                            Region = "Region",
                            UserId = 3
                        },
                        new
                        {
                            EmployeeId = 2,
                            Address = "456 Avenue",
                            Avt = "",
                            City = "City",
                            Country = "Country",
                            Cover = "",
                            Description = "Experienced designer.",
                            FirstName = "Tom",
                            LastName = "Smith",
                            Phone = "0987654321",
                            PostalCode = "67890",
                            Region = "Region",
                            UserId = 5
                        },
                        new
                        {
                            EmployeeId = 3,
                            Address = "789 Boulevard",
                            Avt = "",
                            City = "City",
                            Country = "Country",
                            Cover = "",
                            Description = "Chuyên gia quản lý dự án.",
                            FirstName = "Ngọc",
                            LastName = "Lê",
                            Phone = "1122334455",
                            PostalCode = "54321",
                            Region = "Region",
                            UserId = 7
                        },
                        new
                        {
                            EmployeeId = 4,
                            Address = "101 Parkway",
                            Avt = "",
                            City = "City",
                            Country = "Country",
                            Cover = "",
                            Description = "Kỹ sư phần mềm tài năng.",
                            FirstName = "Minh",
                            LastName = "Phạm",
                            Phone = "2233445566",
                            PostalCode = "98765",
                            Region = "Region",
                            UserId = 9
                        },
                        new
                        {
                            EmployeeId = 5,
                            Address = "202 Circle",
                            Avt = "",
                            City = "City",
                            Country = "Country",
                            Cover = "",
                            Description = "Nhà thiết kế đồ họa sáng tạo.",
                            FirstName = "Huyền",
                            LastName = "Nguyễn",
                            Phone = "3344556677",
                            PostalCode = "87654",
                            Region = "Region",
                            UserId = 11
                        },
                        new
                        {
                            EmployeeId = 6,
                            Address = "303 Lane",
                            Avt = "",
                            City = "City",
                            Country = "Country",
                            Cover = "",
                            Description = "Chuyên viên phân tích dữ liệu.",
                            FirstName = "Nam",
                            LastName = "Trần",
                            Phone = "4455667788",
                            PostalCode = "76543",
                            Region = "Region",
                            UserId = 13
                        },
                        new
                        {
                            EmployeeId = 7,
                            Address = "404 Road",
                            Avt = "",
                            City = "City",
                            Country = "Country",
                            Cover = "",
                            Description = "Quản lý nhân sự có kinh nghiệm.",
                            FirstName = "Lan",
                            LastName = "Hoàng",
                            Phone = "5566778899",
                            PostalCode = "65432",
                            Region = "Region",
                            UserId = 15
                        },
                        new
                        {
                            EmployeeId = 8,
                            Address = "505 Street",
                            Avt = "",
                            City = "City",
                            Country = "Country",
                            Cover = "",
                            Description = "Chuyên gia phát triển phần mềm.",
                            FirstName = "Khánh",
                            LastName = "Đỗ",
                            Phone = "6677889900",
                            PostalCode = "54312",
                            Region = "Region",
                            UserId = 17
                        },
                        new
                        {
                            EmployeeId = 9,
                            Address = "606 Avenue",
                            Avt = "",
                            City = "City",
                            Country = "Country",
                            Cover = "",
                            Description = "Nhà quản lý sản phẩm tài năng.",
                            FirstName = "Quỳnh",
                            LastName = "Vũ",
                            Phone = "7788990011",
                            PostalCode = "43210",
                            Region = "Region",
                            UserId = 19
                        },
                        new
                        {
                            EmployeeId = 10,
                            Address = "707 Plaza",
                            Avt = "",
                            City = "City",
                            Country = "Country",
                            Cover = "",
                            Description = "Chuyên viên IT chuyên nghiệp.",
                            FirstName = "Tùng",
                            LastName = "Bùi",
                            Phone = "8899001122",
                            PostalCode = "32109",
                            Region = "Region",
                            UserId = 21
                        });
                });

            modelBuilder.Entity("FindJobsApplication.Models.EmployeeCertification", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("CertificationId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeCertificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeCertificationId"));

                    b.HasKey("EmployeeId", "CertificationId");

                    b.HasIndex("CertificationId");

                    b.ToTable("EmployeeCertifications");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            CertificationId = 1,
                            EmployeeCertificationId = 0
                        },
                        new
                        {
                            EmployeeId = 1,
                            CertificationId = 2,
                            EmployeeCertificationId = 0
                        },
                        new
                        {
                            EmployeeId = 2,
                            CertificationId = 1,
                            EmployeeCertificationId = 0
                        });
                });

            modelBuilder.Entity("FindJobsApplication.Models.Employer", b =>
                {
                    b.Property<int>("EmployerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployerId"));

                    b.Property<string>("Avt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIBehind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIFront")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyBenefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyFounded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyIndustry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyMission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyProjects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyServices")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanySize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyVision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmployerId");

                    b.HasIndex("UserId");

                    b.ToTable("Employers");

                    b.HasData(
                        new
                        {
                            EmployerId = 1,
                            Avt = "",
                            CompanyName = "Công ty Quản lý Dự án Toàn cầu Ltd.",
                            Cover = "",
                            Description = "Công ty chúng tôi là một trong những đơn vị hàng đầu trong lĩnh vực quản lý dự án toàn cầu, chuyên cung cấp dịch vụ tối ưu cho các doanh nghiệp và tổ chức ở mọi quy mô. Với đội ngũ chuyên gia dày dạn kinh nghiệm trong lĩnh vực quản lý và tư vấn, chúng tôi cam kết mang lại những giải pháp quản lý dự án hiệu quả nhất, giúp khách hàng tối ưu hóa quy trình làm việc, giảm thiểu rủi ro và đạt được mục tiêu kinh doanh một cách nhanh chóng và bền vững. Đặc biệt, chúng tôi luôn áp dụng những công nghệ tiên tiến nhất và các phương pháp quản lý hiện đại để đảm bảo rằng mọi dự án đều được triển khai một cách suôn sẻ và thành công. Với phương châm \"Khách hàng là trung tâm\", chúng tôi luôn sẵn sàng lắng nghe và hiểu rõ nhu cầu của từng khách hàng để cung cấp các giải pháp phù hợp nhất.",
                            Name = "Công ty Quản lý Dự án Toàn cầu",
                            UserId = 2
                        },
                        new
                        {
                            EmployerId = 2,
                            Avt = "",
                            CompanyName = "Công ty Sản xuất Thiết bị Điện tử Ltd.",
                            Cover = "",
                            Description = "Công ty chúng tôi nổi tiếng trong ngành sản xuất thiết bị điện tử, luôn đặt chất lượng sản phẩm lên hàng đầu và chú trọng đến sự hài lòng của khách hàng. Chúng tôi có một đội ngũ kỹ sư và chuyên gia dày dạn kinh nghiệm, không ngừng nghiên cứu và phát triển các sản phẩm mới, đảm bảo đáp ứng được các nhu cầu ngày càng đa dạng của thị trường. Bên cạnh đó, với công nghệ sản xuất hiện đại và quy trình kiểm soát chất lượng nghiêm ngặt, chúng tôi tự hào mang đến cho người tiêu dùng những sản phẩm tiên tiến, an toàn và đáng tin cậy. Chúng tôi cũng cam kết bảo vệ môi trường trong quá trình sản xuất, góp phần vào sự phát triển bền vững của xã hội.",
                            Name = "Công ty Sản xuất Thiết bị Điện tử",
                            UserId = 4
                        },
                        new
                        {
                            EmployerId = 3,
                            Avt = "",
                            CompanyName = "Công ty Phát triển Phần mềm Sáng Tạo Ltd.",
                            Cover = "",
                            Description = "Chúng tôi là công ty chuyên cung cấp các giải pháp phần mềm sáng tạo, giúp các doanh nghiệp hiện đại hóa quy trình làm việc và nâng cao hiệu quả hoạt động. Đội ngũ lập trình viên và chuyên viên tư vấn của chúng tôi không ngừng tìm tòi, sáng tạo và cập nhật công nghệ mới để mang lại cho khách hàng những sản phẩm phần mềm không chỉ tiện ích mà còn độc đáo và tối ưu nhất. Bên cạnh đó, chúng tôi cam kết đồng hành cùng khách hàng từ giai đoạn ý tưởng cho đến khi sản phẩm hoàn thiện và triển khai thành công. Sự hài lòng của khách hàng là động lực lớn nhất để chúng tôi không ngừng phấn đấu và hoàn thiện bản thân.",
                            Name = "Công ty Phát triển Phần mềm Sáng Tạo",
                            UserId = 6
                        },
                        new
                        {
                            EmployerId = 4,
                            Avt = "",
                            CompanyName = "Công ty Xây dựng Hạ Tầng Tiên Phong Ltd.",
                            Cover = "",
                            Description = "Với bề dày kinh nghiệm trong lĩnh vực xây dựng hạ tầng, công ty chúng tôi tự hào là đơn vị tiên phong trong việc cung cấp các giải pháp xây dựng chất lượng cao cho các dự án lớn. Chúng tôi cam kết áp dụng công nghệ và thiết bị hiện đại nhất để đảm bảo rằng mọi công trình đều đạt tiêu chuẩn chất lượng cao nhất và hoàn thành đúng tiến độ. Đội ngũ kỹ sư của chúng tôi luôn sẵn sàng tư vấn và giải quyết mọi vấn đề phát sinh trong quá trình thi công, đảm bảo an toàn và hiệu quả cho từng dự án. Ngoài ra, chúng tôi cũng rất chú trọng đến việc đào tạo và phát triển nguồn nhân lực, giúp nhân viên của chúng tôi phát triển toàn diện cả về chuyên môn và kỹ năng mềm.",
                            Name = "Công ty Xây dựng Hạ Tầng Tiên Phong",
                            UserId = 8
                        },
                        new
                        {
                            EmployerId = 5,
                            Avt = "",
                            CompanyName = "Công ty Dịch Vụ Vận Tải An Toàn Ltd.",
                            Cover = "",
                            Description = "Công ty chúng tôi chuyên cung cấp dịch vụ vận tải an toàn và đáng tin cậy, luôn cam kết mang lại sự hài lòng tối đa cho khách hàng. Với đội xe hiện đại và nhân viên lái xe chuyên nghiệp, chúng tôi sẵn sàng phục vụ khách hàng 24/7, đáp ứng mọi nhu cầu vận chuyển trong thời gian ngắn nhất. Bên cạnh đó, chúng tôi cũng liên tục cải tiến quy trình làm việc và đầu tư vào công nghệ mới nhằm tối ưu hóa chi phí và thời gian cho khách hàng. Đội ngũ chăm sóc khách hàng tận tình của chúng tôi luôn sẵn sàng lắng nghe và đáp ứng mọi yêu cầu của bạn, nhằm đảm bảo rằng trải nghiệm của khách hàng với dịch vụ của chúng tôi luôn là tốt nhất.",
                            Name = "Công ty Dịch Vụ Vận Tải An Toàn",
                            UserId = 10
                        },
                        new
                        {
                            EmployerId = 6,
                            Avt = "",
                            CompanyName = "Công ty Thương Mại Quốc Tế Minh Long Ltd.",
                            Cover = "",
                            Description = "Chuyên gia trong lĩnh vực thương mại quốc tế, chúng tôi cung cấp các giải pháp kinh doanh tối ưu giúp khách hàng mở rộng thị trường và phát triển bền vững. Đội ngũ chuyên viên của chúng tôi luôn nỗ lực tìm kiếm các cơ hội mới và tối ưu hóa quy trình giao dịch quốc tế, đảm bảo rằng khách hàng của chúng tôi luôn đạt được lợi nhuận cao nhất từ các giao dịch thương mại. Với mạng lưới đối tác rộng lớn và uy tín trên toàn cầu, chúng tôi tự tin mang đến cho khách hàng những giải pháp tốt nhất và hỗ trợ tận tình trong từng bước đi của khách hàng trên thị trường quốc tế.",
                            Name = "Công ty Thương Mại Quốc Tế Minh Long",
                            UserId = 12
                        },
                        new
                        {
                            EmployerId = 7,
                            Avt = "",
                            CompanyName = "Công ty Dịch Vụ Tài Chính Hưng Thịnh Ltd.",
                            Cover = "",
                            Description = "Chúng tôi cung cấp dịch vụ tài chính đáng tin cậy, giúp khách hàng quản lý tài sản và đầu tư hiệu quả thông qua sự tư vấn chuyên nghiệp từ các chuyên gia hàng đầu trong ngành. Với nhiều năm kinh nghiệm hoạt động, chúng tôi cam kết mang đến cho khách hàng những giải pháp tài chính linh hoạt, phù hợp với nhu cầu cá nhân hoặc doanh nghiệp. Đội ngũ tư vấn viên tận tâm của chúng tôi sẽ làm việc chặt chẽ với từng khách hàng để đảm bảo rằng mọi quyết định đầu tư đều được đưa ra một cách chính xác và có lợi nhất, nhằm tối ưu hóa giá trị tài sản của bạn.",
                            Name = "Công ty Dịch Vụ Tài Chính Hưng Thịnh",
                            UserId = 14
                        },
                        new
                        {
                            EmployerId = 8,
                            Avt = "",
                            CompanyName = "Công ty Xuất Nhập Khẩu Phúc Lợi Ltd.",
                            Cover = "",
                            Description = "Công ty chúng tôi nổi bật trong lĩnh vực xuất nhập khẩu, chuyên cung cấp những sản phẩm và dịch vụ tốt nhất, đáp ứng nhu cầu đa dạng của thị trường trong và ngoài nước. Chúng tôi có mạng lưới đối tác rộng khắp, đảm bảo cung cấp sản phẩm chất lượng với giá cả cạnh tranh nhất. Đội ngũ nhân viên giàu kinh nghiệm và am hiểu thị trường quốc tế của chúng tôi luôn sẵn sàng hỗ trợ khách hàng từ khâu tìm kiếm nguồn cung ứng cho đến khâu vận chuyển, giúp khách hàng tiết kiệm thời gian và chi phí. Chúng tôi cũng cam kết bảo vệ quyền lợi của khách hàng và đảm bảo rằng mọi giao dịch đều minh bạch và công bằng.",
                            Name = "Công ty Xuất Nhập Khẩu Phúc Lợi",
                            UserId = 16
                        },
                        new
                        {
                            EmployerId = 9,
                            Avt = "",
                            CompanyName = "Công ty Đầu Tư Bất Động Sản Nam Phong Ltd.",
                            Cover = "",
                            Description = "Chúng tôi chuyên cung cấp các giải pháp đầu tư bất động sản sáng tạo, giúp khách hàng tối đa hóa lợi nhuận từ các dự án đầu tư của mình. Với đội ngũ chuyên viên dày dạn kinh nghiệm trong ngành, chúng tôi cam kết mang đến cho khách hàng những tư vấn chuyên sâu và chính xác nhất về xu hướng thị trường và các cơ hội đầu tư tiềm năng. Bên cạnh đó, chúng tôi cũng hỗ trợ khách hàng trong việc quản lý và phát triển các dự án bất động sản, đảm bảo mang lại giá trị gia tăng tối đa cho các khoản đầu tư của bạn và đồng hành cùng bạn trong suốt quá trình đầu tư.",
                            Name = "Công ty Đầu Tư Bất Động Sản Nam Phong",
                            UserId = 18
                        },
                        new
                        {
                            EmployerId = 10,
                            Avt = "",
                            CompanyName = "Công ty Truyền Thông & Quảng Cáo Đỉnh Cao Ltd.",
                            Cover = "",
                            Description = "Chúng tôi là công ty hàng đầu trong lĩnh vực truyền thông và quảng cáo, chuyên cung cấp các giải pháp marketing hiệu quả giúp thương hiệu của bạn tỏa sáng giữa đám đông. Với đội ngũ sáng tạo và dày dạn kinh nghiệm, chúng tôi luôn cập nhật các xu hướng mới nhất trong ngành và xây dựng những chiến dịch quảng cáo độc đáo, thu hút sự chú ý của khách hàng. Đội ngũ nhân viên của chúng tôi sẽ làm việc chặt chẽ với bạn từ giai đoạn ý tưởng cho đến khi triển khai chiến dịch, đảm bảo rằng mọi khía cạnh của thương hiệu đều được chăm sóc và phát triển một cách tốt nhất, từ việc xây dựng hình ảnh cho đến việc tương tác với khách hàng trên các nền tảng truyền thông xã hội.",
                            Name = "Công ty Truyền Thông & Quảng Cáo Đỉnh Cao",
                            UserId = 20
                        });
                });

            modelBuilder.Entity("FindJobsApplication.Models.Hire", b =>
                {
                    b.Property<int>("HireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HireId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobApplyId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("HireId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("JobApplyId");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("Hires");

                    b.HasData(
                        new
                        {
                            HireId = 1,
                            EmployeeId = 1,
                            EmployerId = 1,
                            HireDate = new DateTime(2024, 10, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7433),
                            JobApplyId = 1,
                            JobId = 1,
                            Status = 0
                        },
                        new
                        {
                            HireId = 2,
                            EmployeeId = 2,
                            EmployerId = 1,
                            HireDate = new DateTime(2024, 10, 14, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7440),
                            JobApplyId = 2,
                            JobId = 1,
                            Status = 0
                        },
                        new
                        {
                            HireId = 3,
                            EmployeeId = 3,
                            EmployerId = 2,
                            HireDate = new DateTime(2024, 10, 19, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7443),
                            JobApplyId = 3,
                            JobId = 2,
                            Status = 0
                        });
                });

            modelBuilder.Entity("FindJobsApplication.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.HasKey("InvoiceId");

                    b.HasIndex("EmployerId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceId = 1,
                            Amount = 150m,
                            EmployerId = 1,
                            IssueDate = new DateTime(2024, 10, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7487)
                        },
                        new
                        {
                            InvoiceId = 2,
                            Amount = 200m,
                            EmployerId = 2,
                            IssueDate = new DateTime(2024, 10, 19, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7489)
                        });
                });

            modelBuilder.Entity("FindJobsApplication.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<int>("JobCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("JobType")
                        .HasColumnType("int");

                    b.Property<int?>("Location")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("JobCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobId = 1,
                            DateFrom = new DateTime(2024, 10, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7193),
                            DateTo = new DateTime(2024, 11, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7209),
                            Description = "Phát triển ứng dụng.",
                            EmployerId = 1,
                            IsClosed = false,
                            JobCategoryId = 1,
                            JobType = 0,
                            Salary = 60000m,
                            Title = "Lập trình viên phần mềm"
                        },
                        new
                        {
                            JobId = 2,
                            DateFrom = new DateTime(2024, 10, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7224),
                            DateTo = new DateTime(2024, 12, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7225),
                            Description = "Tạo các trang web đẹp.",
                            EmployerId = 1,
                            IsClosed = false,
                            JobCategoryId = 1,
                            JobType = 0,
                            Salary = 50000m,
                            Title = "Nhà thiết kế web"
                        },
                        new
                        {
                            JobId = 3,
                            DateFrom = new DateTime(2024, 10, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7229),
                            DateTo = new DateTime(2025, 1, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7230),
                            Description = "Nâng cao trải nghiệm người dùng.",
                            EmployerId = 2,
                            IsClosed = false,
                            JobCategoryId = 1,
                            JobType = 1,
                            Salary = 55000m,
                            Title = "Nhà thiết kế UX/UI"
                        },
                        new
                        {
                            JobId = 4,
                            DateFrom = new DateTime(2024, 10, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7233),
                            DateTo = new DateTime(2024, 11, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7234),
                            Description = "Bán sản phẩm và tư vấn khách hàng.",
                            EmployerId = 3,
                            IsClosed = false,
                            JobCategoryId = 4,
                            JobType = 1,
                            Salary = 30000m,
                            Title = "Nhân viên bán hàng"
                        },
                        new
                        {
                            JobId = 5,
                            DateFrom = new DateTime(2024, 10, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7236),
                            DateTo = new DateTime(2024, 12, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7237),
                            Description = "Dạy kèm học sinh cấp 2 và cấp 3.",
                            EmployerId = 4,
                            IsClosed = false,
                            JobCategoryId = 5,
                            JobType = 1,
                            Salary = 20000m,
                            Title = "Gia sư Toán"
                        },
                        new
                        {
                            JobId = 6,
                            DateFrom = new DateTime(2024, 10, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7240),
                            DateTo = new DateTime(2024, 11, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7240),
                            Description = "Phục vụ khách hàng trong nhà hàng.",
                            EmployerId = 5,
                            IsClosed = false,
                            JobCategoryId = 6,
                            JobType = 1,
                            Salary = 25000m,
                            Title = "Phục vụ nhà hàng"
                        },
                        new
                        {
                            JobId = 7,
                            DateFrom = new DateTime(2024, 10, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7243),
                            DateTo = new DateTime(2024, 11, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7244),
                            Description = "Nhập dữ liệu vào hệ thống quản lý.",
                            EmployerId = 6,
                            IsClosed = false,
                            JobCategoryId = 7,
                            JobType = 1,
                            Salary = 22000m,
                            Title = "Nhân viên nhập liệu"
                        },
                        new
                        {
                            JobId = 8,
                            DateFrom = new DateTime(2024, 10, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7246),
                            DateTo = new DateTime(2024, 11, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7247),
                            Description = "Giải đáp thắc mắc và hỗ trợ khách hàng.",
                            EmployerId = 7,
                            IsClosed = false,
                            JobCategoryId = 8,
                            JobType = 1,
                            Salary = 27000m,
                            Title = "Nhân viên chăm sóc khách hàng"
                        },
                        new
                        {
                            JobId = 9,
                            DateFrom = new DateTime(2024, 10, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7250),
                            DateTo = new DateTime(2024, 12, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7250),
                            Description = "Giao hàng tới các địa chỉ yêu cầu.",
                            EmployerId = 8,
                            IsClosed = false,
                            JobCategoryId = 9,
                            JobType = 1,
                            Salary = 30000m,
                            Title = "Nhân viên giao hàng"
                        },
                        new
                        {
                            JobId = 10,
                            DateFrom = new DateTime(2024, 10, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7253),
                            DateTo = new DateTime(2024, 12, 24, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7254),
                            Description = "Pha chế đồ uống theo yêu cầu của khách hàng.",
                            EmployerId = 9,
                            IsClosed = false,
                            JobCategoryId = 10,
                            JobType = 1,
                            Salary = 28000m,
                            Title = "Nhân viên pha chế"
                        });
                });

            modelBuilder.Entity("FindJobsApplication.Models.JobApply", b =>
                {
                    b.Property<int>("JobApplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobApplyId"));

                    b.Property<DateTime>("ApplyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployerId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsAccept")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRefuse")
                        .HasColumnType("bit");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<decimal?>("JobSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("JobApplyId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("JobId");

                    b.ToTable("JobApplies");

                    b.HasData(
                        new
                        {
                            JobApplyId = 1,
                            ApplyDate = new DateTime(2024, 10, 9, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7388),
                            EmployeeId = 1,
                            IsAccept = false,
                            IsRefuse = false,
                            JobId = 1,
                            Status = 0
                        },
                        new
                        {
                            JobApplyId = 2,
                            ApplyDate = new DateTime(2024, 10, 12, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7395),
                            EmployeeId = 2,
                            IsAccept = false,
                            IsRefuse = false,
                            JobId = 1,
                            Status = 0
                        },
                        new
                        {
                            JobApplyId = 3,
                            ApplyDate = new DateTime(2024, 10, 12, 14, 1, 23, 923, DateTimeKind.Local).AddTicks(7398),
                            EmployeeId = 3,
                            IsAccept = false,
                            IsRefuse = false,
                            JobId = 2,
                            Status = 0
                        });
                });

            modelBuilder.Entity("FindJobsApplication.Models.JobCategory", b =>
                {
                    b.Property<int>("JobCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobCategoryId"));

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobCategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobCategoryId");

                    b.ToTable("JobCategory");

                    b.HasData(
                        new
                        {
                            JobCategoryId = 1,
                            Image = "https://e7.pngegg.com/pngimages/169/909/png-clipart-computer-icons-source-code-software-developer-computer-programming-computer-software-software-ico-angle-logo.png",
                            JobCategoryName = "Phát triển phần mềm"
                        },
                        new
                        {
                            JobCategoryId = 2,
                            Image = "https://e7.pngegg.com/pngimages/758/371/png-clipart-web-development-web-service-web-developer-digital-marketing-develop-trademark-logo.png",
                            JobCategoryName = "Thiết Kế Web"
                        },
                        new
                        {
                            JobCategoryId = 3,
                            Image = "https://www.applify.com.sg/blog/wp-content/uploads/2023/09/Key-Differences-Between-UX-Designer-vs.-UI-Designer.png",
                            JobCategoryName = "Thiết kế UX/UI"
                        },
                        new
                        {
                            JobCategoryId = 4,
                            Image = "https://static.thenounproject.com/png/1085397-200.png ",
                            JobCategoryName = "Nhân viên bán hàng"
                        },
                        new
                        {
                            JobCategoryId = 5,
                            Image = "https://logowik.com/content/uploads/images/education635.logowik.com.webp",
                            JobCategoryName = "Gia sư"
                        },
                        new
                        {
                            JobCategoryId = 6,
                            Image = "https://e7.pngegg.com/pngimages/282/85/png-clipart-catering-restaurant-waiter-logo-chef-mart-restaurant-supply-food-vertebrate-thumbnail.png",
                            JobCategoryName = "Phục vụ nhà hàng"
                        },
                        new
                        {
                            JobCategoryId = 7,
                            Image = "https://e7.pngegg.com/pngimages/547/96/png-clipart-data-entry-clerk-paper-service-computer-services-miscellaneous-blue.png",
                            JobCategoryName = "Nhân viên nhập liệu"
                        },
                        new
                        {
                            JobCategoryId = 8,
                            Image = "https://media.istockphoto.com/id/1133541602/vector/hotline-support-service-with-headphones-icon-isolated-on-white-background-vector-illustration.jpg?s=612x612&w=0&k=20&c=81lT8-ARXAeMJzDY7JbzguDoEGSro-GjTomnROdTT3M=",
                            JobCategoryName = "Chăm sóc khách hàng"
                        },
                        new
                        {
                            JobCategoryId = 9,
                            Image = "https://i.pinimg.com/736x/ac/02/83/ac02831601243c01d22fdfc98cc45eec.jpg",
                            JobCategoryName = "Nhân viên giao hàng"
                        },
                        new
                        {
                            JobCategoryId = 10,
                            Image = "https://cdn.vectorstock.com/i/500p/02/85/cocktail-shaker-vector-37740285.jpg",
                            JobCategoryName = "Nhân viên pha chế"
                        });
                });

            modelBuilder.Entity("FindJobsApplication.Models.JobService", b =>
                {
                    b.Property<int>("JobServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobServiceId"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobServiceId");

                    b.HasIndex("AdminId");

                    b.ToTable("JobServices");

                    b.HasData(
                        new
                        {
                            JobServiceId = 1,
                            AdminId = 1,
                            Description = "Đăng Tuyển Dụng.",
                            Price = 100m,
                            ServiceName = "Đăng tin tuyển dụng"
                        },
                        new
                        {
                            JobServiceId = 2,
                            AdminId = 1,
                            Description = "Làm nổi bật tin tuyển dụng của bạn.",
                            Price = 150m,
                            ServiceName = "Nổi Bật Tuyển Dụng"
                        });
                });

            modelBuilder.Entity("FindJobsApplication.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            Comment = "Công việc rất tốt!",
                            EmployeeId = 1,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 2,
                            Comment = "Hiệu suất tốt.",
                            EmployeeId = 2,
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 3,
                            Comment = "Công việc tuyệt vời!",
                            EmployeeId = 1,
                            Rating = 5
                        });
                });

            modelBuilder.Entity("FindJobsApplication.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("AdminId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@example.com",
                            IsBanned = false,
                            PasswordHash = "admin123",
                            Phone = "0123456789",
                            UserType = 0,
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "employer1@example.com",
                            IsBanned = false,
                            PasswordHash = "employer123",
                            Phone = "0123456456",
                            UserType = 1,
                            Username = "employer1"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "employee1@example.com",
                            IsBanned = false,
                            PasswordHash = "employee123",
                            Phone = "0111111111",
                            UserType = 2,
                            Username = "employee1"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "employer2@example.com",
                            IsBanned = false,
                            PasswordHash = "employer123",
                            Phone = "0999999999",
                            UserType = 1,
                            Username = "employer2"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "employee2@example.com",
                            IsBanned = false,
                            PasswordHash = "employee123",
                            Phone = "0123123123",
                            UserType = 2,
                            Username = "employee2"
                        },
                        new
                        {
                            UserId = 6,
                            Email = "employer3@example.com",
                            IsBanned = false,
                            PasswordHash = "employer123",
                            Phone = "0987654321",
                            UserType = 1,
                            Username = "employer3"
                        },
                        new
                        {
                            UserId = 7,
                            Email = "employee3@example.com",
                            IsBanned = false,
                            PasswordHash = "employee123",
                            Phone = "0122222222",
                            UserType = 2,
                            Username = "employee3"
                        },
                        new
                        {
                            UserId = 8,
                            Email = "employer4@example.com",
                            IsBanned = false,
                            PasswordHash = "employer123",
                            Phone = "0988888888",
                            UserType = 1,
                            Username = "employer4"
                        },
                        new
                        {
                            UserId = 9,
                            Email = "employee4@example.com",
                            IsBanned = false,
                            PasswordHash = "employee123",
                            Phone = "0133333333",
                            UserType = 2,
                            Username = "employee4"
                        },
                        new
                        {
                            UserId = 10,
                            Email = "employer5@example.com",
                            IsBanned = false,
                            PasswordHash = "employer123",
                            Phone = "0977777777",
                            UserType = 1,
                            Username = "employer5"
                        },
                        new
                        {
                            UserId = 11,
                            Email = "employee5@example.com",
                            IsBanned = false,
                            PasswordHash = "employee123",
                            Phone = "0133333333",
                            UserType = 2,
                            Username = "employee5"
                        },
                        new
                        {
                            UserId = 12,
                            Email = "employer6@example.com",
                            IsBanned = false,
                            PasswordHash = "employer123",
                            Phone = "0977777777",
                            UserType = 1,
                            Username = "employer6"
                        },
                        new
                        {
                            UserId = 13,
                            Email = "employee6@example.com",
                            IsBanned = false,
                            PasswordHash = "employee123",
                            Phone = "0133333333",
                            UserType = 2,
                            Username = "employee6"
                        },
                        new
                        {
                            UserId = 14,
                            Email = "employer7@example.com",
                            IsBanned = false,
                            PasswordHash = "employer123",
                            Phone = "0977777777",
                            UserType = 1,
                            Username = "employer7"
                        },
                        new
                        {
                            UserId = 15,
                            Email = "employee7@example.com",
                            IsBanned = false,
                            PasswordHash = "employee123",
                            Phone = "0133333333",
                            UserType = 2,
                            Username = "employee7"
                        },
                        new
                        {
                            UserId = 16,
                            Email = "employer8@example.com",
                            IsBanned = false,
                            PasswordHash = "employer123",
                            Phone = "0977777777",
                            UserType = 1,
                            Username = "employer8"
                        },
                        new
                        {
                            UserId = 17,
                            Email = "employee8@example.com",
                            IsBanned = false,
                            PasswordHash = "employee123",
                            Phone = "0133333333",
                            UserType = 2,
                            Username = "employee8"
                        },
                        new
                        {
                            UserId = 18,
                            Email = "employer9@example.com",
                            IsBanned = false,
                            PasswordHash = "employer123",
                            Phone = "0977777777",
                            UserType = 1,
                            Username = "employer9"
                        },
                        new
                        {
                            UserId = 19,
                            Email = "employee9@example.com",
                            IsBanned = false,
                            PasswordHash = "employee123",
                            Phone = "0133333333",
                            UserType = 2,
                            Username = "employee9"
                        },
                        new
                        {
                            UserId = 20,
                            Email = "employer10@example.com",
                            IsBanned = false,
                            PasswordHash = "employer123",
                            Phone = "0977777777",
                            UserType = 1,
                            Username = "employer10"
                        },
                        new
                        {
                            UserId = 21,
                            Email = "employee10@example.com",
                            IsBanned = false,
                            PasswordHash = "employee123",
                            Phone = "0133333333",
                            UserType = 2,
                            Username = "employee10"
                        });
                });

            modelBuilder.Entity("FindJobsApplication.Models.Admin", b =>
                {
                    b.HasOne("FindJobsApplication.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FindJobsApplication.Models.Employee", b =>
                {
                    b.HasOne("FindJobsApplication.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FindJobsApplication.Models.EmployeeCertification", b =>
                {
                    b.HasOne("FindJobsApplication.Models.Certification", "Certification")
                        .WithMany("EmployeeCertifications")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindJobsApplication.Models.Employee", "Employee")
                        .WithMany("EmployeeCertifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certification");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("FindJobsApplication.Models.Employer", b =>
                {
                    b.HasOne("FindJobsApplication.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FindJobsApplication.Models.Hire", b =>
                {
                    b.HasOne("FindJobsApplication.Models.Employee", "Employee")
                        .WithMany("Hires")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FindJobsApplication.Models.Employer", "Employer")
                        .WithMany("Hires")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FindJobsApplication.Models.JobApply", "JobApply")
                        .WithMany()
                        .HasForeignKey("JobApplyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FindJobsApplication.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindJobsApplication.Models.User", null)
                        .WithMany("Hires")
                        .HasForeignKey("UserId");

                    b.Navigation("Employee");

                    b.Navigation("Employer");

                    b.Navigation("Job");

                    b.Navigation("JobApply");
                });

            modelBuilder.Entity("FindJobsApplication.Models.Invoice", b =>
                {
                    b.HasOne("FindJobsApplication.Models.Employer", "Employer")
                        .WithMany("Invoices")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("FindJobsApplication.Models.Job", b =>
                {
                    b.HasOne("FindJobsApplication.Models.Employer", "Employer")
                        .WithMany("PostedJobs")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindJobsApplication.Models.JobCategory", "JobCategory")
                        .WithMany("Jobs")
                        .HasForeignKey("JobCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FindJobsApplication.Models.User", null)
                        .WithMany("Jobs")
                        .HasForeignKey("UserId");

                    b.Navigation("Employer");

                    b.Navigation("JobCategory");
                });

            modelBuilder.Entity("FindJobsApplication.Models.JobApply", b =>
                {
                    b.HasOne("FindJobsApplication.Models.Employee", "Employee")
                        .WithMany("JobApplies")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FindJobsApplication.Models.Employer", null)
                        .WithMany("JobApplies")
                        .HasForeignKey("EmployerId");

                    b.HasOne("FindJobsApplication.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("FindJobsApplication.Models.JobService", b =>
                {
                    b.HasOne("FindJobsApplication.Models.Admin", "Admin")
                        .WithMany("JobServices")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("FindJobsApplication.Models.Review", b =>
                {
                    b.HasOne("FindJobsApplication.Models.Employee", "Employee")
                        .WithMany("Reviews")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindJobsApplication.Models.User", null)
                        .WithMany("Reviews")
                        .HasForeignKey("UserId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("FindJobsApplication.Models.User", b =>
                {
                    b.HasOne("FindJobsApplication.Models.Admin", null)
                        .WithMany("BannedUsers")
                        .HasForeignKey("AdminId");
                });

            modelBuilder.Entity("FindJobsApplication.Models.Admin", b =>
                {
                    b.Navigation("BannedUsers");

                    b.Navigation("JobServices");
                });

            modelBuilder.Entity("FindJobsApplication.Models.Certification", b =>
                {
                    b.Navigation("EmployeeCertifications");
                });

            modelBuilder.Entity("FindJobsApplication.Models.Employee", b =>
                {
                    b.Navigation("EmployeeCertifications");

                    b.Navigation("Hires");

                    b.Navigation("JobApplies");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("FindJobsApplication.Models.Employer", b =>
                {
                    b.Navigation("Hires");

                    b.Navigation("Invoices");

                    b.Navigation("JobApplies");

                    b.Navigation("PostedJobs");
                });

            modelBuilder.Entity("FindJobsApplication.Models.JobCategory", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("FindJobsApplication.Models.User", b =>
                {
                    b.Navigation("Hires");

                    b.Navigation("Jobs");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
